version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: smokeuser
      POSTGRES_PASSWORD: smokepass
      POSTGRES_DB: smokedb
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smokeuser -d smokedb"]
      interval: 3s
      timeout: 3s
      retries: 10

  bot:
    build: .
    env_file:
      - .env.smoke
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "echo '⏳ Waiting for DB...' &&
               sleep 5 &&
               alembic upgrade head &&
               pytest tests/smoke -v --disable-warnings"
