version: "3.9"

services:
  bot:
    build: .
    container_name: saasbot_test_bot
    volumes:
      - .:/app
    env_file:
      - .env.test
    environment:
      - PYTHONPATH=/app
    command: pytest -vv --disable-warnings --maxfail=1
    depends_on:
      test_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started


  test_db:
    image: postgres:15
    container_name: saasbot_test_db
    restart: unless-stopped
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: saasbot_test_redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: saasbot_test_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9100:9000"
      - "9101:9001"
    tmpfs:
      - /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: saasbot_test_network
