global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets: ['bot:8080']   # бот слушает healthz и metrics
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8080']
